#pragma once

#include <stdint.h>

/*
 * Lobster pixel art 32x32 en RGB565.
 * Palette : orange=#FD6A2F (0xFCA5), rouge=#E8321E (0xE183),
 *           rouge fonce=#A0180A (0xA0C1), yeux=#FFFFFF (0xFFFF),
 *           pupilles=#000000 (0x0000), fond=transparent (0x0000)
 *
 * Frames :
 * - lobster_idle    : yeux ouverts, pinces en bas
 * - lobster_blink   : yeux fermes
 * - lobster_think1  : pinces levees, yeux a gauche
 * - lobster_think2  : pinces levees, yeux a droite
 * - lobster_think3  : pinces levees, yeux en haut
 */

#define LOBSTER_W 32
#define LOBSTER_H 32

/* Couleurs RGB565 */
#define C_BG    0x0000  /* fond transparent/noir */
#define C_OR    0xFCA5  /* orange vif */
#define C_RD    0xE183  /* rouge */
#define C_DK    0xA0C1  /* rouge fonce */
#define C_WH    0xFFFF  /* blanc (yeux) */
#define C_BK    0x0000  /* noir (pupilles) - meme que fond, differencie par position */
#define C_LO    0xFBE0  /* orange clair (highlights) */

/* Macro : on definit les sprites en arrays compacts.
 * Chaque sprite = 32*32 = 1024 pixels = 2048 octets.
 * Total 5 frames = ~10 KB flash — negligeable. */

static const uint16_t lobster_idle[LOBSTER_W * LOBSTER_H] = {
    /* Ligne 0-3 : pinces gauche et droite */
    C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_OR,C_LO,C_LO,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_LO,C_LO,C_OR,C_BG,C_BG,C_BG,
    C_BG,C_OR,C_LO,C_BG,C_BG,C_LO,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_LO,C_BG,C_BG,C_LO,C_OR,C_BG,C_BG,
    C_BG,C_OR,C_OR,C_LO,C_LO,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_LO,C_LO,C_OR,C_OR,C_BG,C_BG,
    /* Ligne 4-5 : bras */
    C_BG,C_BG,C_OR,C_OR,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_OR,C_OR,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,
    /* Ligne 6-7 : bras vers le corps */
    C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    /* Ligne 8-9 : antennes */
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    /* Ligne 10-13 : tete avec yeux */
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_WH,C_WH,C_WH,C_RD,C_RD,C_RD,C_RD,C_WH,C_WH,C_WH,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_WH,C_BK,C_WH,C_RD,C_RD,C_RD,C_RD,C_WH,C_BK,C_WH,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_WH,C_WH,C_WH,C_RD,C_RD,C_RD,C_RD,C_WH,C_WH,C_WH,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    /* Ligne 14-15 : bouche */
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_DK,C_DK,C_DK,C_DK,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    /* Ligne 16-19 : corps central */
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    /* Ligne 20-23 : segments abdomen */
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_DK,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_DK,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_DK,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_DK,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    /* Ligne 24-27 : queue (nageoire) */
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_DK,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_DK,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_DK,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_DK,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_OR,C_OR,C_OR,C_OR,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    /* Ligne 28-29 : pattes */
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    /* Ligne 30-31 : fin des pattes */
    C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
};

/* Frame blink : yeux fermes (lignes 11-13 modifiees — yeux = traits horizontaux) */
static const uint16_t lobster_blink[LOBSTER_W * LOBSTER_H] = {
    /* Lignes 0-10 identiques a idle */
    C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_OR,C_LO,C_LO,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_LO,C_LO,C_OR,C_BG,C_BG,C_BG,
    C_BG,C_OR,C_LO,C_BG,C_BG,C_LO,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_LO,C_BG,C_BG,C_LO,C_OR,C_BG,C_BG,
    C_BG,C_OR,C_OR,C_LO,C_LO,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_LO,C_LO,C_OR,C_OR,C_BG,C_BG,
    C_BG,C_BG,C_OR,C_OR,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_OR,C_OR,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    /* Ligne 11-13 : yeux fermes (traits) */
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_DK,C_DK,C_DK,C_RD,C_RD,C_RD,C_RD,C_DK,C_DK,C_DK,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    /* Lignes 14-31 identiques a idle */
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_DK,C_DK,C_DK,C_DK,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_DK,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_DK,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_DK,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_DK,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_DK,C_RD,C_RD,C_RD,C_RD,C_RD,C_RD,C_DK,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_DK,C_BG,C_OR,C_RD,C_RD,C_RD,C_RD,C_OR,C_BG,C_DK,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_OR,C_OR,C_OR,C_OR,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
    C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,C_OR,C_OR,C_BG,C_BG,C_BG,C_BG,C_BG,C_BG,
};

/* Index des frames pour les animations */
#define LOBSTER_FRAME_IDLE   0
#define LOBSTER_FRAME_BLINK  1

/* Table des frames */
static const uint16_t *lobster_frames[] = {
    lobster_idle,
    lobster_blink,
};
#define LOBSTER_FRAME_COUNT  2
